application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  postgresql.image:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  postgresql.volumeSize:
    type: integer
    title: Volume
    description: The size of Volume (Gi) in the solution
    default: 24
  postgresql.serviceAccount:
    type: string
    title: PostgreSQL Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
  db.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 12

required:
- name
- namespace
- postgresql.image
- postgresql.volumeSize
- postgresql.serviceAccount
- db.password
