application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  sonarqube.repository:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  sonarqube.volumeSize:
    type: integer
    title: Volume
    description: The size of Volume (Gi) in the solution
    default: 24
  postgresql.db.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 12
  postgresql.volumeSize:
    type: integer
    title: Volume
    description: The size of Volume (Gi) in the solution
    default: 24
  postgresql.image:
    type: string
    default: $REGISTRY/postgresql9:$TAG
    x-google-marketplace:
      type: IMAGE

required:
- name
- namespace
- sonarqube.repository
- sonarqube.volumeSize
- postgresql.volumeSize
- postgresql.db.password
- postgresql.image
