apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name}}-exts
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 30Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name}}-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 30Gi