replicaCount: 1
sonarqube:
  image: marketplace.gcr.io/google/sonarqube7:latest
  pullPolicy: Always
  volumeSize: 5
  service:
    name: sonarqube
    type: LoadBalancer
    externalPort: 9000
    internalPort: 9000
postgresql:
  image: marketplace.gcr.io/google/postgresql9:latest
  exporter:
    image: null
  volumeSize: 10
  db:
    password: null
    test:
    name: sonar
    user: sonar
  service:
    Port: 5432
    name: postgresql-service
metrics:
  image: null
  enabled: false
